import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/lib/component/Nav";
import Footer from "@/lib/component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Making the whole page flex so the Navbar and the Footer allways 
        on their place even if page conent is empty */}
        <main className="flex flex-col justify-between min-h-screen">
          <div>
            <Nav />
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
